// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission8_2_5.Models;

namespace Mission8_2_5.Migrations
{
    [DbContext(typeof(TaskSubmissionContext))]
    partial class TaskSubmissionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission8_2_5.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("categoryName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryId");

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            categoryName = "Home"
                        },
                        new
                        {
                            CategoryId = 2,
                            categoryName = "School"
                        },
                        new
                        {
                            CategoryId = 3,
                            categoryName = "Work"
                        },
                        new
                        {
                            CategoryId = 4,
                            categoryName = "Church"
                        });
                });

            modelBuilder.Entity("Mission8_2_5.Models.Task", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("completed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("dueDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("quadrant")
                        .HasColumnType("INTEGER");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CategoryId = 1,
                            TaskName = "Apply for internships",
                            completed = false,
                            dueDate = "2023-01-01",
                            quadrant = 3
                        },
                        new
                        {
                            TaskId = 2,
                            CategoryId = 2,
                            TaskName = "Finish Mission 8",
                            completed = false,
                            dueDate = "2023-02-24",
                            quadrant = 2
                        });
                });

            modelBuilder.Entity("Mission8_2_5.Models.Task", b =>
                {
                    b.HasOne("Mission8_2_5.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
